name: Attendance Sync

on:
  schedule:
    - cron: "0 6 * * *"   # every day at 06:00 UTC
  workflow_dispatch:       # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install spond gspread google-auth google-auth-oauthlib pandas openpyxl python-dateutil

      - name: Run attendance sync
        env:
          SPOND_USERNAME: ${{ secrets.SPOND_USERNAME }}
          SPOND_PASSWORD: ${{ secrets.SPOND_PASSWORD }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python attendance_sync_summary.py
