name: Spond Attendance Sync

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install spond gspread google-auth pandas

      - name: Run sync
        env:
          SPOND_USERNAME: ${{ secrets.SPOND_USERNAME }}
          SPOND_PASSWORD: ${{ secrets.SPOND_PASSWORD }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          # Wide fetch window is fine; the script still hard-filters > 2025-07-01
          PAST_DAYS: "730"
          FUTURE_DAYS: "365"
        run: python attendance_sync.py
